export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const GET_UNITS = 'GET_UNITS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const CREATE_INGREDIENT = 'CREATE_INGREDIENT';
export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_SEARCH_DROPDOWN =
  'GET_RECIPES_SEARCH_DROPDOWN';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const OPEN_CREATE_RECIPE_MODAL =
  'OPEN_CREATE_RECIPE_MODAL';
export const CLOSE_CREATE_RECIPE_MODAL =
  'CLOSE_CREATE_RECIPE_MODAL';
export const CHANGE_CREATE_RECIPE_STEP =
  'CHANGE_CREATE_RECIPE_STEP';
export const GET_SEARCH_HISTORY = 'GET_SEARCH_HISTORY';
export const GET_POPULAR_SEARCHES = 'GET_POPULAR_SEARCHES';
export const ADD_TO_SEARCH_HISTORY =
  'ADD_TO_SEARCH_HISTORY';
export const REMOVE_FROM_SEARCH_HISTORY =
  'REMOVE_FROM_SEARCH_HISTORY';
export const CLEAN_SEARCH_HISTORY = 'CLEAN_SEARCH_HISTORY';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SEARCH_DROPDOWN =
  'GET_USERS_SEARCH_DROPDOWN';
